include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - _archive/**
    - archive/**
    - third_party/flutter_callkit_incoming/example/**
    - third_party/flutter_callkit_incoming/test/**
